<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{c7c736b2-d542-4c88-91fe-68de5eef900f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	a:INT;
	b:INT;
	c:INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>